const sprites = [
    'adventurer',
    'avataaars',
    'big-ears',
    'avataaars',
    'big-smile',
    'bottts',
    'croodles',
    'fun-emoji',
    'icons',
    'identicon',
    'lorelei',
    'micah',
    'miniavs',
    'open-peeps',
    'personas',
    'pixel-art',
    'shapes',
    'thumbs',
]
export default sprites
